service:
  name: lyrebird-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
       - dynamodb:Scan
       - dynamodb:PutItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/lyrebird-tasks"
    - Effect: "Allow"
      Action: 
       - s3:PutObject
      Resource: "arn:aws:s3:::lyrebird-uploads/*"
    - Effect: "Allow"
      Action: 
       - s3:GetObject
      Resource: "arn:aws:s3:::lyrebird-completion/*"
custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules

package:
  include:
    - src/**/*.js
  exclude:
    - src/__snapshots__/**
    - src/**/*.test.js
    - .git/**

functions:
  upload:
    handler: src/api.upload
    events:
      - http:
          path: /upload
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
  # download:
  #   handler: src/api.download
  #   events:
  #     - http:
  #         path: /download
  #         method: get
  #         cors:
  #           origins:
  #             - '*'
  #           headers:
  #             - Content-Type
  #             - X-Amz-Date
  #             - Authorization
  #             - X-Api-Key